# Generated by Django 5.1.8 on 2026-03-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='template_id',
            field=models.CharField(choices=[('minimal', 'Minimal Developer Template'), ('dark', 'Dark Developer Theme'), ('cards', 'Modern Card Layout'), ('professional', 'Professional Template'), ('creative', 'Creative Template')], default='minimal', max_length=20),
        ),
    ]
