# Generated by Django 5.1.8 on 2026-03-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_alter_portfolio_template_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
